### ISSUE TITLE
regex failure on return

### ISSUE THREAD

**Issue by joshp23** [ThePasteBin/KiwiIRC-ThePasteBin#1]
I have KiwiIRC-ThePasteBin plugin installed using this settings.json 

> var ThePasteBin = {
>     /*
>       You must first get an API key from: https://api.thepasteb.in/
>       NOTE: Registration is currently closed while in BETA.
>             Please contact us here https://thepasteb.in/contact/ for access.
>     */
>     apikey: '73efd6bd-6ea4-44bd-0000-000000000000',
>     wxh: { // The embed width and height.
>         width: '100%',
>         height: 340,
>         parent: '95%' // The width of the iframe parent.
>     },
>     minlength: 30, // The minimum length for pastes.
>     /*
>       DO NOT EDIT BELOW THIS POINT UNLESS YOU KNOW WHAT YOU'RE DOING!
>       One day TheP(aste)B.in may go open source; make these editable!
>     */
>     title: 'TheP(aste)B.in', // The name of the pastebin.
>     LightBox: {
>         global: false, // Give all plugins access to the LightBox.
>     },
>     url: 'https://{{:sub|api-sandbox.}}thepasteb.in/{{:endpoint| }}{{:extras| }}',
>     endpoints: {
>         embed: 'v1/oembed/',
>         paste: 'v1/paste/submit/',
>     },
>     regex: /^https?:\/\/(?:.+\.)?thepasteb\.in\/[pet]\/.+/i
> };

 to generate the plugin file. It pastes well, and returns a valid link, but when I attempt to get the drop-down box in the room, it returns this error

> Bad Request - child "url" fails because ["url" with value "https://sandbox.thepasteb.in/p/98hRJ750pORuk" fails to match the required pattern: /^(?:https?:\/\/(?:.+\\.)?thepb\.in\/[pet]\/)?([a-z0-9]+)(?:\/?(#[a-z0-9\,\-]+)|\/([a-z]+)(?:\/([a-z0-9]+)\/?)?)?\/?$/i]

Where is this coming from?

**Comment by LouisT** [comment]
Hello, this was a mistake on the server side in the API sandbox server. I had forgotten to update the regex to support the new domain, but all is fixed now.
